# Generated by Django 3.2.16 on 2022-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookshelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(to='core.BookShelf'),
        ),
    ]
